name: Commit e PR - Main

on:
  push:
    branches:
       - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Teste binário
      run: npm run test
